package com.savina.service;

import com.savina.model.Ticket;
import com.savina.model.User;

import java.sql.SQLException;
import java.sql.*;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import com.savina.model.TicketType;
import com.savina.model.TicketStatus;

public class TicketService {

    private static String DbUsername = "soft";
    private static String DbPassword = "1";
    private static String DbUrl = "jdbc:oracle:thin:@localhost:1521/XEPDB1";

    public List<Ticket> searchTickets() {
        // kërkim biletash (placeholder)
        return null;
    }

    public Ticket buyTicket(String email, TicketType ticketType) {

        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            con.setAutoCommit(false);

            // 1️⃣ Merr USER_ID nga email
            String userSql = "SELECT user_id FROM USERI WHERE email = ?";
            pst = con.prepareStatement(userSql);
            pst.setString(1, email);
            rs = pst.executeQuery();

            if (!rs.next()) {
                throw new RuntimeException("User nuk ekziston me këtë email");
            }

            int userId = rs.getInt("user_id");
            pst.close();

            // 2️⃣ Krijo ticket
            Ticket ticket = new Ticket();
            ticket.setTicketType(ticketType);
            ticket.setPrice(ticketType.getPrice());
            ticket.setStatus(TicketStatus.BOUGHT);
            ticket.setQrCode(UUID.randomUUID().toString());

            // 3️⃣ Insert ticket (ticket_id autogenerated nga SEQUENCE)
            String sql = "INSERT INTO TICKET "
                    + "(ticket_id, user_id, ticket_type, price, status, qr_code) "
                    + "VALUES (TICKET_SEQ.NEXTVAL, ?, ?, ?, ?, ?)";

            pst = con.prepareStatement(sql);
            pst.setInt(1, userId);                       // NUMBER ✅
            pst.setString(2, ticketType.name());         // VARCHAR ✅
            pst.setDouble(3, ticket.getPrice());         // NUMBER ✅
            pst.setString(4, ticket.getStatus().name());
            pst.setString(5, ticket.getQrCode());

            pst.executeUpdate();
            con.commit();

            System.out.println("Ticket bought successfully: " + ticket.getQrCode());

            return ticket;

        } catch (Exception e) {
            e.printStackTrace();
            try { if (con != null) con.rollback(); } catch (SQLException ignored) {}
            return null;

        } finally {
            try { if (rs != null) rs.close(); } catch (Exception ignored) {}
            try { if (pst != null) pst.close(); } catch (Exception ignored) {}
            try { if (con != null) con.close(); } catch (Exception ignored) {}
        }
    }


    public boolean activateTicket(Ticket ticket) {
        ticket.setStatus(TicketStatus.ACTIVE);
        ticket.setActivationDate(new Date());
        return true;
    }

    public boolean checkValidity(Ticket ticket) {
        Date today = new Date();
        return ticket.getExpirationDay().after(today);
    }

    public String generateQRCode(Ticket ticket) {
        String qrCode = UUID.randomUUID().toString();
        ticket.setQrCode(qrCode);
        return qrCode;
    }
}
